apiVersion: apps/v1
kind: Deployment
metadata:
  name: standard-host-path-nfs-pvc-deployment
  labels:
    app: standard-host-path-nfs-pvc-deployment
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: standard-host-path-nfs-pvc-pod
  template:
    metadata:
      labels:
        app: standard-host-path-nfs-pvc-pod
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: standard-host-path-nfs-pvc-pod
      containers:
      - name: pause
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - 'echo $(hostname) >> /my-test/hello.txt ; sleep infinity'
        volumeMounts:
        - name: volv
          mountPath: /my-test
        ports:
        - containerPort: 80
        resources: {}
      volumes:
      - name: volv
        persistentVolumeClaim:
          claimName: nfs-claim