apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim
  namespace: test
spec:
  storageClassName: nfs-client-provisioner
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 128Mi
