apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim
  namespace: test
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 128Mi