---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: soarca
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/thijs-flux/soarca-deploy
