apiVersion: v1
kind: Service
metadata:
  namespace: apps
  name: soarca
spec:
  type: ClusterIP
  selector:
    app: soarca
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http