apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-storage-0
  namespace: monitoring
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 128Mi