apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m
  chart: loki
  sourceRef:
    kind: HelmRepository
    name: grafana-charts
  version: "6.38"
  valuesFiles:
    - values.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m
  chartRef:
    kind: HelmChart
    name: loki
    namespace: monitoring