---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: networking
spec:
  addresses:
  # - 192.168.67.17-192.168.67.255
    - ${addresspool}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: announcement
  namespace: networking
spec:
  ipAddressPools:
  - first-pool
