apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: apps
  labels:
    reachable: external
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80