---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: networking
spec:
  interval: 10m
  chart: cilium
  sourceRef:
    kind: HelmRepository
    name: cilium
  version: "1.18"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: networking
spec:
  interval: 5m
  chartRef:
    kind: HelmChart
    name: cilium
    namespace: networking
  values:
    ipam:
      mode: kubernetes
    hostFirewall:
      enabled: true
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
      peerService:
        clusterDomain: "cluster.local"
    etcd:
      clusterDomain: localhost
    kubeProxyReplacement: true
    securityContext:
      capabilities:
        ciliumAgent:
        - CHOWN
        - KILL
        - NET_ADMIN
        - NET_RAW
        - IPC_LOCK
        - SYS_ADMIN
        - SYS_RESOURCE
        - DAC_OVERRIDE
        - FOWNER
        - SETGID
        - SETUID
        cleanCiliumState:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE
    cgroup:
      autoMount:
        enabled: true
      hostRoot: /sys/fs/cgroup
    k8sServiceHost: "auto"
    k8sServicePort: "6443"
    nodePort:
      enabled: true
    l7Proxy: true
    gatewayAPI:
      enabled: true