---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: networking
spec:
  interval: 10m
  chart: cilium
  sourceRef:
    kind: HelmRepository
    name: cilium
  version: "1.18"
  valuesFiles:
    - values.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: networking
spec:
  interval: 5m
  chartRef:
    kind: HelmChart
    name: cilium
    namespace: networking