---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: deny-ingress
spec:
  endpointSelector:
    matchLabels:
      {}
  ingress:
    - fromEntities:
      - kube-apiserver
    - fromEndpoints:
      - matchLabels:
          namespace: flux-system
    - fromEndpoints:
      - matchLabels:
          namespace: kube-system
  ingressDeny:
    - fromEntities:
      - world
---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-external-access
spec:
  endpointSelector:
    matchLabels:
      reachable: "external"
  ingress:
  - fromEntities:
    - world
---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-cluster-access
spec:
  endpointSelector:
    matchLabels:
      reachable: "cluster"
  ingress:
  - fromEntities:
    - cluster
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: monitoring
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      {}
  ingress:
    - fromEndpoints:
      - matchLabels:
          component: monitoring
    - fromEntities:
      - host