---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istiod
  namespace: networking
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istiod
  namespace: networking
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istiod-binding
  namespace: networking
subjects:
- kind: ServiceAccount
  name: istiod
  namespace: networking
roleRef:
  kind: ClusterRole
  name: istiod
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: istio
  namespace: networking
spec:
  interval: 5m0s
  url: https://istio-release.storage.googleapis.com/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: istio-base
  namespace: networking
spec:
  interval: 10m
  chart: base
  sourceRef:
    kind: HelmRepository
    name: istio
  version: "1.27"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: networking
spec:
  interval: 5m
  chartRef:
    kind: HelmChart
    name: istio-base
    namespace: networking
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: istio-control
  namespace: networking
spec:
  interval: 10m
  chart: istiod
  sourceRef:
    kind: HelmRepository
    name: istio
  version: "1.27"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-control
  namespace: networking
spec:
  interval: 5m
  chartRef:
    kind: HelmChart
    name: istio-control
    namespace: networking
  values:
    profile: "ambient"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: istio-cni
  namespace: networking
spec:
  interval: 10m
  chart: cni
  sourceRef:
    kind: HelmRepository
    name: istio
  version: "1.27"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: networking
spec:
  interval: 5m
  chartRef:
    kind: HelmChart
    name: istio-cni
    namespace: networking
  values:
    profile: "ambient"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: istio-ztunnel
  namespace: networking
spec:
  interval: 10m
  chart: ztunnel
  sourceRef:
    kind: HelmRepository
    name: istio
  version: "1.27"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ztunnel
  namespace: networking
spec:
  interval: 5m
  chartRef:
    kind: HelmChart
    name: istio-ztunnel
    namespace: networking