---
apiVersion: v1

kind: Service

metadata:
  name: wireguard
  namespace: networking

spec:
  type: LoadBalancer
  ports:
    - name: wireguard
      port: 51820
      protocol: UDP
      targetPort: 51820
  selector:
    name: wireguard