apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
namespace: nfs-provisioner
resources:
  - github.com/kubernetes-sigs/nfs-subdir-external-provisioner//deploy
patches:
  # - path: patch.yaml
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          app: nfs-client-provisioner
        name: nfs-client-provisioner
      spec:
        template:
          spec:
            containers:
              - name: nfs-client-provisioner
                env:
                  - name: NFS_SERVER
                    value: "${nfs_server}"
                  - name: NFS_PATH
                    value: /Share
            volumes:
              - name: nfs-client-root
                nfs:
                  server: "${nfs_server}"
                  path: /Share
spec:
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars

