apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soarca-doc
  namespace: apps
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 128Mi