apiVersion: v1
kind: Service
metadata:
  namespace: apps
  name: soarca-doc
spec:
  type: ClusterIP
  selector:
    app: soarca-doc
  ports:
    - name: soarca-doc-http
      port: 80
      protocol: TCP
      targetPort: soarca-doc-port
